/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.encrypto.EncryptoClient;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EncryptoClientTest {
    @Test void appHasAGreeting() {
        EncryptoClient classUnderTest = new EncryptoClient();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
